version: "3.9"
services:
  localhost:
    image: postgres
    container_name: pg_database
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - 5433:5432
    volumes:
      - ./schemas/schemaFile.sql:/docker-entrypoint-initdb.d/schemaFile.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
  charmander_backend:
      depends_on:
        db:
          condition: service_healthy
      build: .
      environment:
        - PORT=${PORT}
        - DB_HOST=${DB_HOST}
        - DB_USER=${DB_USER}
        - DB_DATABASE=${DB_DATABASE}
        - DB_PASSWORD=${DB_PASSWORD}
      ports:
        - 3000:3000


