version: "3.9"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./schemas/schemaFile.sql:/docker-entrypoint-initdb.d/schemaFile.sql